# Generated by Django 3.1.7 on 2021-03-21 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
