# Generated by Django 3.1.7 on 2021-03-21 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_resource'),
        ('party', '0002_delete_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_count', models.IntegerField(default=1)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='locations.location')),
                ('member', models.ManyToManyField(related_name='party', to='party.Character')),
            ],
        ),
    ]
