# Generated by Django 3.1.7 on 2021-03-21 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0003_party'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='member',
            new_name='members',
        ),
    ]
