# Generated by Django 3.1.7 on 2021-03-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0004_auto_20210321_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='gold',
            field=models.FloatField(default=0),
        ),
    ]
