# Generated by Django 3.1.7 on 2021-03-22 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_resource'),
        ('party', '0005_party_gold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='party', to='party.party')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='locations.resource')),
            ],
        ),
        migrations.AddField(
            model_name='party',
            name='inventory',
            field=models.ManyToManyField(through='party.Inventory', to='locations.Resource'),
        ),
    ]
