# Generated by Django 3.1.7 on 2021-03-22 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0006_auto_20210322_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='resource_set', to='party.party'),
        ),
    ]
