# Generated by Django 3.1.7 on 2021-03-22 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_resource'),
        ('party', '0007_auto_20210322_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='party_history_set', to='locations.location')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='history_set', to='party.party')),
            ],
        ),
        migrations.AddField(
            model_name='party',
            name='history',
            field=models.ManyToManyField(related_name='history', through='party.History', to='locations.Location'),
        ),
    ]
