# Generated by Django 3.1.7 on 2021-03-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0010_remove_history_visit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='visit_count',
            field=models.IntegerField(default=1),
        ),
    ]
