# Generated by Django 3.1.7 on 2021-04-01 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0011_history_visit_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_set', to='party.party'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_set', to='party.party'),
        ),
    ]
