# Generated by Django 3.1.7 on 2021-04-01 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20210401_1911'),
        ('party', '0012_auto_20210401_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_count', models.IntegerField(default=1)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='party_history_set', to='locations.location')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travelhistory_set', to='party.party')),
            ],
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.AlterField(
            model_name='party',
            name='history',
            field=models.ManyToManyField(related_name='history', through='party.TravelHistory', to='locations.Location'),
        ),
    ]
