# Generated by Django 3.1.7 on 2021-04-01 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20210401_1911'),
        ('party', '0013_auto_20210401_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='history',
            new_name='travel_history',
        ),
        migrations.AlterField(
            model_name='travelhistory',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='travel_history_set', to='locations.location'),
        ),
        migrations.AlterField(
            model_name='travelhistory',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_history_set', to='party.party'),
        ),
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_spent', models.FloatField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trade_history_set', to='locations.location')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trade_history_set', to='party.party')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='locations.resource')),
            ],
        ),
    ]
