# Generated by Django 3.1.7 on 2021-04-03 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0014_auto_20210401_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradehistory',
            old_name='quantity',
            new_name='quantity_gained',
        ),
    ]
