# Generated by Django 3.1.7 on 2021-04-04 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0015_auto_20210403_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradehistory',
            name='location',
        ),
        migrations.AddField(
            model_name='tradehistory',
            name='location_hist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_history_set', to='party.travelhistory'),
        ),
    ]
