# Generated by Django 3.1.7 on 2021-04-05 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0016_auto_20210404_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='travelhistory',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='tradehistory',
            old_name='money_spent',
            new_name='gold_gained',
        ),
    ]
