# Generated by Django 3.1.7 on 2021-04-01 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='probability',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='LocationResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_speciality', models.BooleanField(default=False)),
                ('base_value', models.FloatField(default=None, null=True)),
                ('probability', models.FloatField(default=None, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.resource')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='resources',
            field=models.ManyToManyField(related_name='custom_resources', through='locations.LocationResource', to='locations.Resource'),
        ),
    ]
