# Generated by Django 3.1.7 on 2021-04-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_locationresource_variance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='probability',
            field=models.FloatField(default=None, null=True),
        ),
    ]
